coverage:
  branch: master
  bot: null

  status:
    precision: 2
    round: down
    range: "70...100"

    project:
      default:
        target: 0%
        branches: null
        threshold: null
        # threshold: 3
        # Fail the status if coverage drops by >= 3%

    patch:
      default:
        target: 0%
        branches: null
        # threshold: 3
    
    changes:
      default:
        branches: null

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default